### PR TITLE
Update SetupWifi.md

### PR DESCRIPTION
**Pull request by matinlotfali**
Removing the `networkd-wait-online` comment because it was causing the long wait time.

### CODE REVIEW

**Comment by mistyron** [comment]
> Removing the `networkd-wait-online` comment because it was causing the long wait time.

But the only edit in the PR is in `content/SetupWifi.md`, please review!

**Review by mistyron — CHANGES_REQUESTED** [review]
Only content/SetupWifi.md is edited in this PR

**Comment by matinlotfali** [comment]
> > Removing the `networkd-wait-online` comment because it was causing the long wait time.
> 
> But the only edit in the PR is in `content/SetupWifi.md`, doesn't align with your PR description, please review!

How is it not aligned? I don't understand the issue.

**Review by mistyron — APPROVED** [review]
re-reviewed :eyes:  LGTM  :+1:

**Pull request merged**
